### ISSUE TITLE
devtools::check() running infinite while devtools::test() running fine

### ISSUE THREAD

**Issue by pat-s** [hadley/testthat#567]
When running `devtools::test()` on my [package](https://github.com/pat-s/sperrorest), everything works fine. 

`devtools::check()` and `R CMD check` are running infinite on my tests. My tests are using two cores via `foreach()`. Is that causing trouble? If not, is there any way to debug this?

(Please use the `dev` branch for testing purposes.)

**Comment by xrobin** [comment]
I am running into exactly the same issue with one of my package right now.
I tried to isolate a minimal example and pushed it into [xrobin/testParallel](https://github.com/xrobin/testParallel). 
Basically, just opening and closing a cluster with a function such as the following is sufficient to trigger the infinite run:

```
startStopCluster <- function() {
	cl <- makeCluster(2)
	stopCluster(cl)
	return(1)
}
```
Commenting out `test_check("testParallel")` in `tests/testthat.R` in order to have the function tested outside of testthat is sufficient to have the tests finish quickly (indicating this is not a problem with `R CMD check` itself).

**Comment by gaborcsardi** [comment]
This is the infamous `R_TESTS` catch. See https://github.com/xrobin/testParallel/pull/1/files#diff-3cf6fd2c31bb0259d6cfae004cdf115cR3 for the fix.

**Comment by xrobin** [comment]
This fixed the issue right away. It also shows how poor my googling skills are - even with the solution I can't really understand what's going on.
I hope it solves the problem for pat-s too.
Thanks a lot!

**Comment by pat-s** [comment]
Wow, that solved the problem! How many hours did I spent on that...

Thanks so much!!!! @gaborcsardi

**Comment by michaelbarton** [comment]
Thank you, this solved this issue for me to. For anyone coming here from google. Add:

    Sys.unsetenv("R_TESTS")

For testing parallel functions with testthat.
