### ISSUE TITLE
Why are `expect_` functions all titled with questions?

### ISSUE THREAD

**Issue by katrinleinweber** [hadley/testthat#606]
Hello! I have the above, maybe naive, maybe language question about the docu for all the `expect_` functions (for example [`expect_equal`: `Expectation: is the object equal to a value?`](https://github.com/hadley/testthat/blob/master/R/expect-equality.R#L1)). Doesn't an expectation imply that something _is_, not whether it might be this or that? I'm not a native English speaker, though! Maybe I am missing an obvious rationale for using `?`here?

I started using `testthat` regularly through [Exercism.io's R track](https://github.com/exercism/r) and am sometimes confused by the report about a failed test. Sometimes, there are `x[1]: ` and `y[1]: ` listed with some results, or `Lengths differ: … vs …`, and it's not clear which is the expected and which is the actual result. OTOH `… not equal to …` in a report makes it perfectly clear :-)

Thus, as an occasional testthat user, I wondered how the output or the docu could be updated in order to improve the understanding of reports about failed tests. I feel motivated to work on rewording the titles, in order to specify which expectation exactly needs to be met in order to make test pass. In case of `expect_equal` for example: `Expectation: The object is equal to a value.`.

Would that be a useful contribution here?

**Comment by hadley** [comment]
I think of an expectation as a question: is the output what I expect? Does it equal this? Or throw that error?

But maybe your problem is not so much with the titles of the documentation but the individual failure messages? I'll fix the issue with "vs" here, but please feel free to file more issues whenever you encounter confusing output. Your perspective as a new user of testthat is particularly valuable!
